Progress bar bug fix

diff --git a/supreme-1.3.1/kbcm b/supreme-1.3.1/kbcm
--- a/supreme-1.3.1/kbcm
+++ b/supreme-1.3.1/kbcm
@@ -66,9 +66,13 @@ if [[ $# -ne 3 ]]; then
 kbcmusage && exit 0
 fi
 tots=$(szcum "$2")
-if [ "$tots" == "f" ]
+if [[ "$tots" == "f" ]]
 then
 echo -e "\e[91mSource path not found\e[0m"
+exit 0
+elif [[ ! -d "$3" ]]
+then
+echo -e "\e[91mDestination path not found\e[0m"
 exit 0
 else
 feedemt=$(echo "$2" | rev | cut -d '/' -f 1 | rev)
@@ -77,9 +81,13 @@ $actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots" || exit 1
 	if [[ ${PIPESTATUS[0]} == 1 ]]
 	then
 		tots=$(szcum "$2")
-		if [ "$tots" == "f" ]
+		if [[ "$tots" == "f" ]]
 		then
 		echo -e "\e[91mSource path not found\e[0m"
+		exit 1
+		elif [[ ! -d "$3" ]]
+		then
+		echo -e "\e[91mDestination path not found\e[0m"
 		exit 1
 		else
 		feedemt=$(echo "$2" | rev | cut -d '/' -f 1 | rev)
