kbcm new version Remove diff check while moving due to performance issues Faster deletions from phone storage

diff --git a/supreme-1.3.7/kbcm b/supreme-1.3.7/kbcm
--- a/supreme-1.3.7/kbcm
+++ b/supreme-1.3.7/kbcm
@@ -54,12 +54,14 @@ EOF
 }
 #------------------------------------------------------------------------------------------------
 OPTIND=1
-unset eqchk
+actnskip="y"
 while getopts ":cmv" option; do
   	case "${option}" in
-	c)actn="cp -r";;
-	m)actn="mv -f";;
-	v)echo -e "version 1.1.0" && exit 0;;
+	c)actn="cp -rf"
+	  lbl="COPY";;
+	m)actn="mv -f"
+	  lbl="MOVE";;
+	v)echo -e "version 1.1.1" && exit 0;;
 	\?)kbcmusage && exit 0;;
 	esac
 done
@@ -77,81 +79,71 @@ echo -e "\e[91mDestination path not found\e[0m"
 exit 0
 else
 feedemt=$(echo "$2" | rev | cut -d '/' -f 1 | rev)
-colorfmt "$2 --> $3"
-	if [[ "$2" == *"/$UID/gvfs/mtp"* ]] || [[ "$3" == *"/$UID/gvfs/mtp"* ]]
+colorfmt "$2 --$lbl--> $3"
+	if [[ -d "$3"/"$feedemt" ]] || [[ -f "$3"/"$feedemt" ]]
 	then
-		if [[ "$2" != *"/$UID/gvfs/mtp"* ]] && [[ "$actn" == "mv -f" ]]
-		then
-		(cp -r "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
-			if [[ ${PIPESTATUS[0]} == 1 ]]
-			then
-			echo -e "\e[91m❌️ Failed\e[0m"
-			else
-				if [[ -d "$3"/"$feedemt" ]] || [[ -f "$3"/"$feedemt" ]]
-				then
-					if [[ -d "$2" ]] || [[ -f "$2" ]]
-					then
-					echo -e "Waiting for checks to finish..."
-					eqchk=$(diff -r "$2" "$3"/"$feedemt")
-						if [[ -z "$eqchk" ]]
-						then
-						sudo rm -rf "$2"
-						echo -e "\e[92m✔️ Done\e[0m"
-						unset eqchk
-						else
-						echo -e "\e[91m❌️ Failed\e[0m"
-						fi
-					fi
-				fi
-			fi)
-		else
-		($actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
-			if [[ ${PIPESTATUS[0]} == 1 ]]
-			then
-			echo -e "\e[91m❌️ Failed\e[0m"
-			else
-			echo -e "\e[92m✔️ Done\e[0m"
-			fi)
-		fi
-	else
-	chk3=$(echo "$2" | rev | cut -d/ -f2- | rev )
-	chk4=$(echo "$3" | rev | cut -d/ -f1- | rev )
-	fs3=$(df "$chk3" | awk '{print $1}' | sed 1d)
-	fs4=$(df "$chk4" | awk '{print $1}' | sed 1d)
-		if [[ "$fs3" != "$fs4" ]] && [[ "$actn" == "mv -f" ]]
-		then
-		(sudo cp -r "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
-			if [[ ${PIPESTATUS[0]} == 1 ]]
-			then
-			echo -e "\e[91m❌️ Failed\e[0m"
-			else
-				if [[ -d "$3"/"$feedemt" ]] || [[ -f "$3"/"$feedemt" ]]
-				then
-					if [[ -d "$2" ]] || [[ -f "$2" ]]
-					then
-					echo -e "Waiting for checks to finish..."
-					eqchk=$(diff -r "$2" "$3"/"$feedemt")
-						if [[ -z "$eqchk" ]]
-						then
-						sudo rm -rf "$2"
-						echo -e "\e[92m✔️ Done\e[0m"
-						unset eqchk
-						else
-						echo -e "\e[91m❌️ Failed\e[0m"
-						fi
-					fi
-				fi
-			fi)
-		else
-		(sudo $actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
-			if [[ ${PIPESTATUS[0]} == 1 ]]
-			then
-			echo -e "\e[91m❌️ Failed\e[0m"
-			else
-			echo -e "\e[92m✔️ Done\e[0m"			
-			fi)
-		fi
+	echo -e "\e[91m$feedemt exists in $3. Overwrite? (y/n)\e[0m"
+	read actnskip
 	fi
+	case "$actnskip" in
+	y|Y)if [[ "$2" == *"/$UID/gvfs/mtp"* ]] || [[ "$3" == *"/$UID/gvfs/mtp"* ]]
+	    then
+			if [[ "$2" != *"/$UID/gvfs/mtp"* ]] && [[ "$lbl" == "MOVE" ]]
+			then
+			(cp -r "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
+				if [[ ${PIPESTATUS[0]} == 1 ]]
+				then
+				echo -e "\e[91m❎️ Failed\e[0m"
+				else
+					if [[ -d "$3"/"$feedemt" ]] || [[ -f "$3"/"$feedemt" ]]
+					then
+						if [[ -d "$2" ]] || [[ -f "$2" ]]
+						then
+						sudo rm -rf "$2" && echo -e "\e[92m✔️ Done\e[0m" || echo -e "\e[91m❎️ Failed\e[0m"
+						fi
+					fi
+				fi)
+			else
+			($actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
+				if [[ ${PIPESTATUS[0]} == 1 ]]
+				then
+				echo -e "\e[91m❎️ Failed\e[0m"
+				else
+				echo -e "\e[92m✔️ Done\e[0m"
+				fi)
+			fi
+	     else
+	     chk3=$(echo "$2" | rev | cut -d/ -f2- | rev )
+	     chk4=$(echo "$3" | rev | cut -d/ -f1- | rev )
+	     fs3=$(df "$chk3" | awk '{print $1}' | sed 1d)
+	     fs4=$(df "$chk4" | awk '{print $1}' | sed 1d)
+			if [[ "$fs3" != "$fs4" ]] && [[ "$lbl" == "MOVE" ]]
+			then
+			(sudo cp -r "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
+				if [[ ${PIPESTATUS[0]} == 1 ]]
+				then
+				echo -e "\e[91m❎️ Failed\e[0m"
+				else
+					if [[ -d "$3"/"$feedemt" ]] || [[ -f "$3"/"$feedemt" ]]
+					then
+						if [[ -d "$2" ]] || [[ -f "$2" ]]
+						then
+						sudo rm -rf "$2" && echo -e "\e[92m✔️ Done\e[0m" || echo -e "\e[91m❎️ Failed\e[0m"
+						fi
+					fi
+				fi)
+			else
+			(sudo $actn "$2" "$3" | kbbar "$2" "$3"/"$feedemt" "$tots";
+				if [[ ${PIPESTATUS[0]} == 1 ]]
+				then
+				echo -e "\e[91m❎️ Failed\e[0m"
+				else
+				echo -e "\e[92m✔️ Done\e[0m"			
+				fi)
+			fi
+	    fi;;
+	*)echo -e "\e[91mSkipping $feedemt\e[0m";;
+	esac
 fi
 
 
